"""rewards store

Revision ID: 5b4156b08a59
Revises: d5014fe54d80
Create Date: 2026-08-04 18:23:38.765679

"""
from alembic import op
import sqlalchemy as sa


revision = '5b4156b08a59'
down_revision = 'd5014fe54d80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('cost_points', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rewards'))
    )
    op.create_table('reward_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('points_spent', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_reward_claims_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], name=op.f('fk_reward_claims_reward_id_rewards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reward_claims'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reward_claims')
    op.drop_table('rewards')
    # ### end Alembic commands ###
