"""initial schema

Revision ID: 7c21604f47e1
Revises: 
Create Date: 2026-08-04 16:40:40.334207

"""
from alembic import op
import sqlalchemy as sa


revision = '7c21604f47e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caldav_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('apple_id', sa.String(length=255), nullable=False),
    sa.Column('password_enc', sa.LargeBinary(), nullable=False),
    sa.Column('server_url', sa.String(length=255), nullable=False),
    sa.Column('principal_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("kind IN ('grocery','todo','custom')", name='ck_lists_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recipe_url', sa.String(length=512), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('original_path', sa.String(length=512), nullable=False),
    sa.Column('display_path', sa.String(length=512), nullable=False),
    sa.Column('thumb_path', sa.String(length=512), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_guid', sa.String(length=255), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256'),
    sa.UniqueConstraint('source_guid')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('avatar_path', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('shared_albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=120), nullable=False),
    sa.Column('base_host', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_weather_cache_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('remote_url', sa.String(length=512), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('ctag', sa.String(length=255), nullable=True),
    sa.Column('sync_token', sa.String(length=512), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['caldav_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('remote_url')
    )
    op.create_table('chores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('rrule', sa.String(length=255), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countdowns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(length=12), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('custom_text', sa.String(length=255), nullable=True),
    sa.CheckConstraint("slot IN ('breakfast','lunch','dinner','snack')", name='ck_meal_plan_slot'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'slot', name='uq_meal_plan_date_slot')
    )
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plan_date'), ['date'], unique=False)

    op.create_table('chore_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chore_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chore_id', 'due_date', name='uq_chore_completions')
    )
    with op.batch_alter_table('chore_completions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chore_completions_due_date'), ['due_date'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('remote_href', sa.String(length=512), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('ics', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('dtstart_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dtend_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint("origin IN ('remote','local')", name='ck_events_origin'),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_id', 'uid', name='uq_events_calendar_uid')
    )
    op.create_table('occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('start_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occurrences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occurrences_start_utc'), ['start_utc'], unique=False)

    op.create_table('pending_ops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('op', sa.String(length=10), nullable=False),
    sa.Column('payload_ics', sa.Text(), nullable=True),
    sa.Column('remote_href', sa.String(length=512), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("op IN ('create','update','delete')", name='ck_pending_ops_op'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_ops')
    with op.batch_alter_table('occurrences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occurrences_start_utc'))

    op.drop_table('occurrences')
    op.drop_table('events')
    with op.batch_alter_table('chore_completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chore_completions_due_date'))

    op.drop_table('chore_completions')
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plan_date'))

    op.drop_table('meal_plan')
    op.drop_table('meal_ingredients')
    op.drop_table('list_items')
    op.drop_table('countdowns')
    op.drop_table('chores')
    op.drop_table('calendars')
    op.drop_table('weather_cache')
    op.drop_table('sync_log')
    op.drop_table('shared_albums')
    op.drop_table('settings')
    op.drop_table('profiles')
    op.drop_table('photos')
    op.drop_table('meals')
    op.drop_table('lists')
    op.drop_table('caldav_accounts')
    # ### end Alembic commands ###
