"""event profile tag

Revision ID: 941f8516ee2f
Revises: 7c21604f47e1
Create Date: 2026-08-04 16:48:41.287511

"""
from alembic import op
import sqlalchemy as sa


revision = '941f8516ee2f'
down_revision = '7c21604f47e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_events_profile_id_profiles'), 'profiles', ['profile_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_events_profile_id_profiles'), type_='foreignkey')
        batch_op.drop_column('profile_id')

    # ### end Alembic commands ###
