"""chore groups and per person completion

Revision ID: d5014fe54d80
Revises: 941f8516ee2f
Create Date: 2026-08-04 18:21:02.608931

"""
from alembic import op
import sqlalchemy as sa


revision = 'd5014fe54d80'
down_revision = '941f8516ee2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chore_assignees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chore_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.id'], name=op.f('fk_chore_assignees_chore_id_chores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_chore_assignees_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chore_assignees')),
    sa.UniqueConstraint('chore_id', 'profile_id', name='uq_chore_assignees')
    )
    with op.batch_alter_table('chore_completions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_chore_completions'), type_='unique')
        batch_op.create_unique_constraint('uq_chore_completions_person', ['chore_id', 'due_date', 'profile_id'])
        batch_op.create_foreign_key(batch_op.f('fk_chore_completions_profile_id_profiles'), 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')

    # data backfill: legacy single-person chores become one-member groups,
    # and their past completions are credited to that person
    op.execute(
        "INSERT INTO chore_assignees (chore_id, profile_id) "
        "SELECT id, profile_id FROM chores WHERE profile_id IS NOT NULL"
    )
    op.execute(
        "UPDATE chore_completions SET profile_id = "
        "(SELECT profile_id FROM chores WHERE chores.id = chore_completions.chore_id)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_completions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chore_completions_profile_id_profiles'), type_='foreignkey')
        batch_op.drop_constraint('uq_chore_completions_person', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_chore_completions'), ['chore_id', 'due_date'])
        batch_op.drop_column('profile_id')

    op.drop_table('chore_assignees')
    # ### end Alembic commands ###
