"""event rrule column

Revision ID: dae054c5426c
Revises: 5b4156b08a59
Create Date: 2026-08-05 04:25:31.516026

"""
from alembic import op
import sqlalchemy as sa


revision = 'dae054c5426c'
down_revision = '5b4156b08a59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rrule', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###

    # backfill from each event's stored ICS so already-synced repeating events
    # keep their rule (and don't get flattened by the next edit)
    conn = op.get_bind()
    rows = conn.execute(
        sa.text("SELECT id, ics FROM events WHERE is_recurring = 1")
    ).fetchall()
    for event_id, ics in rows:
        rule = None
        for raw_line in (ics or "").splitlines():
            line = raw_line.strip()
            if line.upper().startswith("RRULE:"):
                rule = line[len("RRULE:"):].strip()
                break
        if rule:
            conn.execute(
                sa.text("UPDATE events SET rrule = :rule WHERE id = :id"),
                {"rule": rule[:255], "id": event_id},
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('rrule')

    # ### end Alembic commands ###
